#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnyPay.Resource", IsApplication=true)]

namespace AnyPay
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int acf_nc_blue_xxhdpi = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int acf_nc_green_xxhdpi = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int acf_nc_red_xxhdpi = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int anypay_icon_a_256 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int anypay_wordmark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CardClip = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Rect = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int CardContainer = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int CardImage = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int CardShortName = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int PMList = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddPaymentMethod = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateAccount = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginAccount = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MenuBar = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Pay = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PaymentMethodList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PaymentMethodRow = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AnyPay_Main = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
