#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnyPay.Resource", IsApplication=true)]

namespace AnyPay
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int showBack = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int showMenu = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int acf_nc_blue_xxhdpi = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int acf_nc_green_xxhdpi = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int acf_nc_red_xxhdpi = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int acf_ncc_blue_xxhdpi = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int acf_ncc_green_xxhdpi = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int acf_ncc_red_xxhdpi = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int anypay_icon_a_256 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int anypay_wordmark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int BackButton = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int CardClip = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_arrow_back_black_48dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_menu_black_48dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int mastercard_base_xxhdpi = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int MenuButton = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Rect = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int visa_base_xxhdpi = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int CardAccountNumber = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int CardContainer = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int CardHolderName = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int CardImage = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int CardShortName = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int LowerCardFields = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int MenuBar = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MenuButtonBack = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int MenuButtonMenu = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int PMList = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int UpperCardFields = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddPaymentMethod = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateAccount = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int LoginAccount = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MenuBar = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Pay = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PaymentMethodList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PaymentMethodRow = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AnyPay_Main = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MenuBar = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MenuBar_showBack = 0;
			
			// aapt resource value: 1
			public const int MenuBar_showMenu = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
